name: Android Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Execute Permission for Gradlew
        run: chmod +x IranianVRStreamer_Quest_Client_V2/gradlew

      - name: Build APK
        working-directory: IranianVRStreamer_Quest_Client_V2
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: QuestClient-Debug
          path: "**/app/build/outputs/apk/debug/*.apk"
